using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid.Views.Grid;
using GTrans.Abstract;
using System.IO;
using System.Drawing.Imaging;
using GTrans.DSDatosTableAdapters;
using ACINOX.DBT.DSDllTableAdapters;

namespace GTrans.Tareas
{
    public partial class FrmEstructura : SaveableForm
    {
        public FrmEstructura(FrmMain main):base (main)
        {
            InitializeComponent();

            HelperAdapter.DoAdapter(tableAdapterManager1);
            // This line of code is generated by Data Source Configuration Wizard
            t_ModeloTableAdapter1.FillByTipoMarca(dsDatos1.T_Modelo, 1);
            t_TipoMantenimientoTableAdapter1.Fill(dsDatos1.T_TipoMantenimiento);
            t_TipoModeloMantTableAdapter1.Fill(dsDatos1.T_TipoModeloMant);
            t_TipoModeloAccionTableAdapter1.Fill(dsDatos1.T_TipoModeloAccion);
            t_MarcaTableAdapter1.FillBy1(dsDatos1.T_Marca,1);
      
        
        }
     

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }
        private bool edited;
        private object _focuseddata;
        public object FocusedData
        {
            get { return _focuseddata; }
            set
            {
                if (value == null)
                {
                    while (tTipoModeloAccionBindingSource.Count > 0)
                        tTipoModeloAccionBindingSource.RemoveCurrent();
                }
                    
                barButtonItem1.ImageIndex = value is DSDatos.T_MarcaRow ? 4 : value is DSDatos.T_ModeloRow ? 5 : value is DSDatos.T_TipoModeloMantRow ? 6 : 7;
             
                barButtonItem2.ImageIndex = value is DSDatos.T_MarcaRow ? 8 : value is DSDatos.T_ModeloRow ? 9 : value is DSDatos.T_TipoModeloMantRow ? 10 : 11;
                barButtonItem3.ImageIndex = value is DSDatos.T_MarcaRow ? 12 : value is DSDatos.T_ModeloRow ? 13 : value is DSDatos.T_TipoModeloMantRow ? 14 :15;
                if (value is DSDatos.T_TipoModeloAccionRow)
                {
                    if (Tag == null && (!(_focuseddata is DSDatos.T_TipoModeloAccionRow)))
                    {
                        Tag = _focuseddata;
                        _focuseddata = value;
                    }
                    else
                        if (edited)
                        {
                            _focuseddata = Tag;
                            Tag = null;
                        }
                        else _focuseddata = value;
                }
                else
                {
                    _focuseddata = value;

                }
                if (!(_focuseddata is DSDatos.T_TipoModeloAccionRow))
                {
                    colnamemodelo1.Visible = _focuseddata is DSDatos.T_MarcaRow;
                    colnametipomantenimiento1.Visible = _focuseddata is DSDatos.T_ModeloRow || colnamemodelo1.Visible;
                }

                if (_focuseddata is DSDatos.T_MarcaRow)
                    t_TipoModeloAccionTableAdapter1.FillBy(dsDatos1.T_TipoModeloAccion, ((DSDatos.T_MarcaRow)_focuseddata).idmarca, "0");
                else
                    if (_focuseddata is DSDatos.T_ModeloRow)
                        t_TipoModeloAccionTableAdapter1.FillBy(dsDatos1.T_TipoModeloAccion, ((DSDatos.T_ModeloRow)_focuseddata).idmodelo, "1");
                    else
                        if (_focuseddata is DSDatos.T_TipoModeloMantRow)
                            t_TipoModeloAccionTableAdapter1.FillBy(dsDatos1.T_TipoModeloAccion, ((DSDatos.T_TipoModeloMantRow)_focuseddata).idtipomodelomant, "2");

            }
        }
        private void barButtonItem4_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            var edit = new FrmEditEstructura();

            edit.SetTitleInfo((Bitmap)imageCollection1.Images[e.Item.ImageIndex], "", "");

            if (e.Item.Tag == null)
                edit.type = _focuseddata is DSDatos.T_MarcaRow ? 0 : _focuseddata is DSDatos.T_ModeloRow ? 1 : _focuseddata is DSDatos.T_TipoModeloMantRow ? 2 : 3;
            else
            {
                edit.type = (int)e.Item.Tag;
                barButtonItem1.Tag = e.Item.Tag;
                barButtonItem1.ImageIndex = e.Item.ImageIndex;
            }
                


            switch (edit.type)
            {
                case 1:
                    {
                        if (_focuseddata != null)
                            if (_focuseddata is DSDatos.T_MarcaRow)
                                edit.idparent = ((DSDatos.T_MarcaRow)_focuseddata).idmarca;
                            else
                                if (_focuseddata is DSDatos.T_ModeloRow)
                                    edit.idparent = ((DSDatos.T_ModeloRow)_focuseddata).idmarca;
                                else
                                    if (_focuseddata is DSDatos.T_TipoModeloMantRow)
                                        edit.idparent = ((DSDatos.T_TipoModeloMantRow)_focuseddata).T_ModeloRow.idmarca;
                                    else
                                        edit.idparent = ((DSDatos.T_TipoModeloAccionRow)_focuseddata).T_TipoModeloMantRow.T_ModeloRow.idmarca;
                        break;
                    }
                case 2:
                    {
                        if (_focuseddata != null)
                            if (_focuseddata is DSDatos.T_MarcaRow) 
                            edit.idparent = -1;
                            else
                                if (_focuseddata is DSDatos.T_ModeloRow)
                                    edit.idparent = ((DSDatos.T_ModeloRow)_focuseddata).idmodelo;
                                else
                                    if (_focuseddata is DSDatos.T_TipoModeloMantRow)
                                        edit.idparent = ((DSDatos.T_TipoModeloMantRow)_focuseddata).idmodelo;
                                    else
                                        edit.idparent = ((DSDatos.T_TipoModeloAccionRow)_focuseddata).T_TipoModeloMantRow.T_ModeloRow.idmodelo;
                        break;
                    }
                case 3:
                    {
                        try
                        {
                            if (_focuseddata != null)
                                if (_focuseddata is DSDatos.T_MarcaRow)
                                  edit.idparent = -1;
                                else
                                    if (_focuseddata is DSDatos.T_ModeloRow) 
                                   edit.idparent = -1;
                                    else
                                        if (_focuseddata is DSDatos.T_TipoModeloMantRow)
                                            edit.idparent = ((DSDatos.T_TipoModeloMantRow)_focuseddata).idtipomodelomant;
                                        else
                                            edit.idparent = ((DSDatos.T_TipoModeloAccionRow)_focuseddata).T_TipoModeloMantRow.idtipomodelomant;

                        }
                        catch (Exception) { }
                        break;
                    }
                default: break;

            }

            if (e.Item.Tag == null)
                edit.edit = _focuseddata is DSDatos.T_MarcaRow ? ((DSDatos.T_MarcaRow)_focuseddata).idmarca : _focuseddata is DSDatos.T_ModeloRow ? ((DSDatos.T_ModeloRow)_focuseddata).idmodelo : _focuseddata is DSDatos.T_TipoModeloMantRow ? ((DSDatos.T_TipoModeloMantRow)_focuseddata).idtipomodelomant : ((DSDatos.T_TipoModeloAccionRow)_focuseddata).idaccionmant;

            else
                edit.edit = -1;


            if (edit.ShowDialog(this) == System.Windows.Forms.DialogResult.OK)
            {
                switch (edit.type)
                {
                    case 0: { t_MarcaTableAdapter1.FillBy1(dsDatos1.T_Marca, 1); break; }
                    case 1: { t_ModeloTableAdapter1.Fill(dsDatos1.T_Modelo); t_TipoModeloMantTableAdapter1.Fill(dsDatos1.T_TipoModeloMant); t_TipoMantenimientoTableAdapter1.Fill(dsDatos1.T_TipoMantenimiento); break; }
                    case 2: { t_TipoModeloMantTableAdapter1.Fill(dsDatos1.T_TipoModeloMant); t_TipoMantenimientoTableAdapter1.Fill(dsDatos1.T_TipoMantenimiento); break; }
                    case 3:
                        {
                            t_TipoMantenimientoTableAdapter1.Fill(dsDatos1.T_TipoMantenimiento);
                            var w = tTipoModeloAccionBindingSource.Position;
                            edited = true;
                            var t = FocusedData;
                            FocusedData = Tag; FocusedData = t;
                            tTipoModeloAccionBindingSource.Position = w;
                            break;
                        }
                    default:
                        break;
                }
            }
        }

        private void gridView1_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            FocusedData = ((DevExpress.XtraGrid.Views.Grid.GridView)sender).GetDataRow(e.FocusedRowHandle);
        }
        private GridView focusdgrid;
        private void gridView1_RowCellClick(object sender, DevExpress.XtraGrid.Views.Grid.RowCellClickEventArgs e)
        {
            FocusedData = ((DevExpress.XtraGrid.Views.Grid.GridView)sender).GetDataRow(((DevExpress.XtraGrid.Views.Grid.GridView)sender).FocusedRowHandle);
            focusdgrid = ((DevExpress.XtraGrid.Views.Grid.GridView)sender);
        }

        private void barButtonItem3_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            var msg = "Esta seguro que desea eliminar ";

            if (_focuseddata is DSDatos.T_MarcaRow)
                msg += "esta marca de equipo";
            else
                if (_focuseddata is DSDatos.T_ModeloRow)
                    msg += "este modelo de equipo";
                else
                    if (_focuseddata is DSDatos.T_TipoModeloMantRow)
                        msg += "esta tipo de mantenimiento";
                    else
                        if (_focuseddata is DSDatos.T_TipoModeloAccionRow)
                            msg += "esta acción";

            msg += " ?";
            if (XtraMessageBox.Show(msg, "Eliminar", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == System.Windows.Forms.DialogResult.Yes)
            {
                HelperAdapter.DeleteRow((DataRow)_focuseddata);

                if (_focuseddata is DSDatos.T_MarcaRow)
                    bindingSource1.RemoveCurrent();

                else
                    if (_focuseddata is DSDatos.T_ModeloRow)
                        focusdgrid.DeleteSelectedRows();


                    else
                        if (_focuseddata is DSDatos.T_TipoModeloMantRow)
                            focusdgrid.DeleteSelectedRows();

                        else
                            if (_focuseddata is DSDatos.T_TipoModeloAccionRow)
                                tTipoModeloAccionBindingSource.RemoveCurrent();


            }
        }

        private void gridView2_RowCellClick(object sender, DevExpress.XtraGrid.Views.Grid.RowCellClickEventArgs e)
        {
            edited = false;

            gridView1_RowCellClick(sender, e);
        }

        private void bindingSource1_CurrentChanged(object sender, EventArgs e)
        {
            object t =null;
            if(bindingSource1.Current!=null)
                t= ((DataRowView)bindingSource1.Current).Row;
     
            FocusedData = t;
            focusdgrid = gridView1;
        }

        private void FrmEstructura_Load(object sender, EventArgs e)
        {

        }
    }
}